language: java

jdk:
  - oraclejdk8

# To build javafx
# https://github.com/travis-ci/travis-ci/issues/3259
## http://blog.travis-ci.com/2015-10-14-opening-up-ubuntu-trusty-beta/
sudo: required
dist: trusty

script:
  - ./gradlew check distTar distZip

# Skip gradle assemble
# Refer to http://stackoverflow.com/questions/26566564/override-default-travis-ci-script-for-java-gradle-project
install: /bin/true
